apiVersion: v1
kind: Service
metadata:
  name: mysql-container-service
spec:
  clusterIP: None
  ports:
  - port: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-container-service
subsets:
  - addresses:
        - ip: 192.168.0.36
    ports:
      - port: 3306
        name: mysql-container-service
