apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-content-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 10Gi
  selector:
    matchLabels:
      volFor: web-content

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: http-conf-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Mi
  selector:
    matchLabels:
      volFor: http-conf
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-conf-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Mi
  selector:
    matchLabels:
      volFor: php-conf

