apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.6
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-container-service
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        - name: php-conf
          mountPath: /usr/local/etc/php/conf.d/
        - name: httpd-conf
          mountPath: /etc/apache2/sites-available/
      volumes:
      - name: wordpress-persistent-storage
        nfs:
          server: 192.168.0.36
          path: /home/donal/samba/wp
      - name: php-conf
        nfs:
          server: 192.168.0.36
          path: /home/donal/samba/php-conf
      - name: httpd-conf
        nfs:
          server: 192.168.0.36
          path: /home/donal/samba/httpd-conf
